name: 🧪 CI · Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: Ref.
        required: false
        default: ''
        type: string

permissions: {}

concurrency:
  group: build-pr-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      packages: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build_common.yml@93dcc244b1713aeb9594aff65df1a2901ded707f
    with:
      ref: ${{ inputs.ref || github.sha }}

  native:
    needs:
      - build
    permissions:
      contents: read
    uses: YunaBraska/YunaBraska/.github/workflows/wc_java_build_native.yml@75c33480e1f7b0286597be8db43ca920ef773865
    with:
      ref: ${{ needs.build.outputs.commit_sha }}
      version: ${{ needs.build.outputs.version }}
